// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "../prisma/schema.prisma", // Updated schema path to match the correct location
  migrations: {
    path: "../prisma/migrations", // Updated migrations path to match the correct location
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
